export const places = [
  { name: "Gosaikunda", type: "Adventure", region: "Langtang" },
  { name: "Rupse Chhahara", type: "Nature", region: "Mustang" },
  {
    name: "Bhaktapur Durbar Square",
    type: "Cultural",
    region: "Central Nepal",
  },
  { name: "Chisapani Gadhi", type: "Traditional", region: "Eastern Nepal" },
  { name: "Rara Lake", type: "Nature", region: "Far Western Nepal" },
  { name: "Annapurna Base Camp", type: "Adventure", region: "Annapurna" },
  { name: "Poon Hill", type: "Adventure", region: "Gandaki" },
  { name: "Lumbini", type: "Cultural", region: "Lumbini" },
  { name: "Mount Everest Base Camp", type: "Adventure", region: "Khumbu" },
  { name: "Patan Durbar Square", type: "Cultural", region: "Kathmandu" },
  { name: "Tinjure Milke Jaljale", type: "Nature", region: "Eastern Nepal" },
  { name: "Barun Valley", type: "Nature", region: "Makalu" },
  { name: "Rangbhang Valley", type: "Adventure", region: "Far Western Nepal" },
  { name: "Nagarkot", type: "Nature", region: "Central Nepal" },
  { name: "Chitwan National Park", type: "Nature", region: "Central Nepal" },
  { name: "Bandipur", type: "Traditional", region: "Central Nepal" },
  { name: "Ghandruk", type: "Traditional", region: "Annapurna" },
  { name: "Ilam Tea Gardens", type: "Traditional", region: "Eastern Nepal" },
  { name: "Shey Phoksundo Lake", type: "Nature", region: "Dolpa" },
  { name: "Langtang Valley", type: "Adventure", region: "Langtang" },
  { name: "Phewa Lake", type: "Nature", region: "Pokhara" },
  { name: "Muktinath", type: "Cultural", region: "Mustang" },
  { name: "Rara National Park", type: "Nature", region: "Far Western Nepal" },
  { name: "Khaptad Dham", type: "Nature", region: "Far Western Nepal" },
  { name: "Daman Hill Station", type: "Nature", region: "Central Nepal" },
];
